### ISSUE TITLE
Tuple cannot be used in the slice declaration

### ISSUE THREAD

**Issue by chrihop** [verus-lang/verus#1259]
In the Verus environment, any place that uses tuples inside the slice (`&[(_, _)]`) will cause a parsing failure:

> ```
> thread 'rustc' panicked at vir/src/poly.rs:144:27:
> internal error: Tuple should be removed by ast_simplify
> ```

Please see the sample code in the code in the [Verus Playground](https://play.verus-lang.org/?version=stable&mode=detailed&edition=2021&gist=2ad8736a2d5d1c8757114fbc22c28581).

**Comment by tjhance** [comment]
I fixed the tuple-related panic. There's now an unrelated issue with the linked code:

This line:
```
const VAL: &[(u8, u8)] = &[(3, 5)];
```

Now gives:

```
error: cannot call function `vstd::array::array_as_slice` with mode exec
 --> tslice.rs:8:26
  |
8 | const VAL: &[(u8, u8)] = &[(3, 5)];
  |                          ^^^^^^^^^
```

This isn't really a bug _per se_ so much as an unsupported feature (though the error msg is kind of confusing). Right now, there are a lot of operations not supported in consts, and the array-to-slice coercion is just one of them. We can probably improve this if we implement something like the [returns proposal](https://github.com/verus-lang/verus/discussions/851) and in particular the [dual-mode support](https://github.com/verus-lang/verus/discussions/851#discussioncomment-9865820). Since we already have a discussion place for this, I'm gonna go ahead and close the issue.
