### ISSUE TITLE
Panic "get_impl_paths nesting depth exceeds 1000"

### ISSUE THREAD

**Issue by zhengyao-lin** [verus-lang/verus#1273]
Hello! I'm hitting [this panic](https://github.com/verus-lang/verus/blob/f5cdebeed5d75d0be78368ad72a9f95754b097f7/source/rust_verify/src/rust_to_vir_base.rs#L446) when adding a let x = term in exec code, where term has a pretty long type (as in the [type itself](https://gist.github.com/zhengyao-lin/5c13f7d1fa2ed636f397629c01a0f732) has a 15-ish depth), along with many trait bounds.

But I'm not entirely sure if the large type is the problem, and I don't quite understand what get_impl_paths does.

[2024-09-19-19-54-05.zip](https://github.com/user-attachments/files/17067997/2024-09-19-19-54-05.zip)

**Comment by tjhance** [comment]
get_impl_paths finds all trait implementations that a certain call or type depends on

it's probably fine to increase this bound. "Depth" is the wrong word here (since it's implemented as a breadth-first search; it's just counting the total number of impls). Having a very high count isn't necessarily a bug, since each generic impls gets counted once for each instantation.

**Comment by tjhance** [comment]
I increased the bound to 100,000. Can you try again?

**Comment by zhengyao-lin** [comment]
Works now. Thanks!

Although I didn't expect there to be 1000 instantiations. I'll check if there's anything wrong.
