### ISSUE TITLE
expand-errors with spec function & type arguments

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#333]
If you run with `--expand-errors`, this code gives an invalid AIR:

```rust
#![allow(unused_imports)]
use builtin::*;
use builtin_macros::*;
use state_machines_macros::*;
mod pervasive;
use pervasive::set::*;

verus!{


spec fn all_contains<A>(s1: Set<A>) -> bool {
    forall |a: A| s1.contains(a)
}


proof fn failing_proof(s: Set<int>)
{
    assert(all_contains(s));
}


}

fn main() { }
```

```
note: verifying root module

error: assertion failed
  --> bug4.rs:18:12
   |
18 |     assert(all_contains(s));
   |            ^^^^^^^^^^^^^^^ assertion failed

thread 'rustc' panicked at 'internal error: generated ill-typed AIR code: error 'in call to pervasive.set.Set.contains.?, argument #3 has type "Int" when it should have type "Poly"' in expression '(pervasive.set.Set.contains.? INT (Poly%pervasive.set.Set<int.>. s~2@) a~8$)'', rust_verify/src/verifier.rs:368:21
```

**Comment by channy412** [comment]
Just to add a bit of information:

This bug happens when we inline `all_contains` at the failing assertion.

While the signature of `contains` is `(Type Poly Poly) -> Bool)` , the inlined expression of `all_contains` is  `forall |a: int| contains(Int, box(s), a)` .  It seems like we need to `box` the last argument `a`. 

When substituting a generic type with a concrete type (substituting `T` with `int` in this case), it seems like we need to`box` the substituting expressions in some cases. 

But I am not sure when we should `box` and shouldn't `box` the substituting expression in general cases of function inlining.

**Comment by tjhance** [comment]
@Chris-Hawblitzel can you take a look this one if you get a chance? looks like it has something to do with boxing so I think the rest of us aren't sure how to approach it

**Comment by tenzinhl** [comment]
Think I ran into the same thing on #561 . Not having it panic and instead being able to see which part of the assertion failed would be helpful for debugging a proof faster

**Comment by Chris-Hawblitzel** [comment]
It should be fixed by https://github.com/verus-lang/verus/commit/4454b0cdc9b86f84021cc4a72fa6a1a0ed603443 .
