### ISSUE TITLE
`is_variant` annotation doesn't handle type parameters with attributes

### ISSUE THREAD

**Issue by tenzinhl** [verus-lang/verus#480]
Issue arose from this PR:
https://github.com/verus-lang/verus/pull/396#issuecomment-1459096776

## Summary
The `is_variant` proc macro currently doesn't handle attributes on type parameters.

From [a comment from @tjhance](https://github.com/verus-lang/verus/pull/396#issuecomment-1459111971):
```
#[is_variant]
enum X<#[verifier(maybe_negative)] T> {
  ZZ(T),
}
```

Causes error output:
```
error: expected one of `>`, a const expression, lifetime, or type, found `#`
  --> test_gen.rs:16:8
   |
16 | enum X<#[verifier(maybe_negative)] T> {
   |        ^ expected one of `>`, a const expression, lifetime, or type
```

Suggested solution is to replace the use of `synstructure` by just parsing an `ItemEnum` using `verus_syn`

**Comment by tjhance** [comment]
I think it may already be parsed by the time this function is called, since it takes a `synstructure::Structure` as input. 

the attribute_is_variant function is called from here: https://github.com/verus-lang/verus/blob/95cecdd5542d020e36e18b22f23d241bf62ae08d/source/builtin_macros/src/lib.rs#L18

I guess `decl_attribute!` is some magic synstructure macro that expands to a function that calls  `attribute_is_variant`. 

There are other functions in lib.rs that use `syn` (rather than `synstructure`) so you can base a replacement off of one of those.

> Also tried inserting panic!'s into https://github.com/verus-lang/verus/blob/main/dependencies/syn/src/lookahead.rs (since I thought this is where the error text was being generated) but no dice there either (did I have to rebuild the dependency separately?)

I think this didn't work because `synstructure` uses the normal rust version of `syn` rather than our fork `verus_syn` (which is the one in our dependencies directory)

**Comment by tjhance** [comment]
@tenzinhl after thinking about it, I'm starting to doubt that my original diagnosis of the problem was correct. I said that it looks like synstructure is unable to parse `#[verifier(maybe_negative)]`, but since synstructure uses the `syn` library under the hood, and `syn` is able to handle attributes on type parameters, it just doesn't make any since that synstructure chokes on this.

I suspect what's actually going on is that the is_variant macro is generating malformed code somehow, by placing the attribute where it isn't expected. I need to look into this more.

(I still think that replacing updating `is_variant` to use `syn_verus` is a good idea, since we want to be able to support any special syntax we add to types or to item declarations. However, I think this is mostly an orthogonal issue to the #[verifier(maybe_negative)] issue. And it probably doesn't matter whether we use `synstructure` or not - though if we _do_ use it, it needs to be backed by `syn_verus` rather than `syn`.)

**Comment by tjhance** [comment]
OK, here's the actual problem.

The is_variant macro uses the following output template

https://github.com/verus-lang/verus/blob/c9203533cbe079c36578830898d1be681430dab6/source/builtin_macros/src/is_variant.rs#L85
```rust
        #[automatically_derived]
        impl#generics #struct_name#generics {
            #is_impls
        }   
```

Note that `#generics` is used twice. Here, `generics` is a syn `Generics` node: https://docs.rs/syn/latest/syn/struct.Generics.html

The `Generics` node is used for type parameter _declarations_ and allows trait bounds, a `where` clause, and attributes, which are all appropriate for type declarations. However, that is problematic for the second use of `generics` in the above snippet. For example, suppose the struct is declared with `T: Copy`. Then the above snippet would output,

```
impl<T: Copy> Foo<T: Copy> { ... }
```

This is a parse error. We actually want to output just,

```
impl<T: Copy> Foo<T> { ... }
```

Likewise, with `#[verifier(maybe_negative)]` we end up outputting:

```
impl<#[verifier(maybe_negative)] T> Foo<#[verifier(maybe_negative)] T> { ... }
```

Again this is a parse error because of the second attribute (though we actually don't need either one here)

To make matters worse, the `Generics` object includes the 'where' clause, but the 'where' clause needs to go after the type. So outputting a correct `impl` line is actually somewhat complicated.

This is something I had to deal with for the state_machines macro as well. See how I handled it there:

https://github.com/verus-lang/verus/blob/c9203533cbe079c36578830898d1be681430dab6/source/state_machines_macros/src/to_token_stream.rs#L171

https://github.com/verus-lang/verus/blob/c9203533cbe079c36578830898d1be681430dab6/source/state_machines_macros/src/to_token_stream.rs#L94

**Comment by tenzinhl** [comment]
Thanks @tjhance :), I'll take a crack at it.

How did you drill down to find the actual problem?

Is it possible to run `verus` somehow and see the incorrect output:
```
impl<#[verifier(maybe_negative)] T> Foo<#[verifier(maybe_negative)] T> { ... }
```

If I'm not misremembering, I tried running `verus` with `-Zunpretty=expanded` but the output didn't contain the "bad stuff" (like it got thrown out before it reached stdout)

**Comment by tenzinhl** [comment]
> You can output a token stream from the macro, although it's pretty hard to read. It gets the job done in a pinch.

Gotchu, like just with a `println!` call?

> Unfortunately, I don't have a satisfying story to tell you...

Gotcha haha, still good to know, thanks.

**Comment by tjhance** [comment]
> Gotchu, like just with a println! call?

yeah, you can do `println!("{:}", token_stream)` or something. Don't remember off the top of my head.

**Comment by tjhance** [comment]
You can either get it as an array of the internal representation of tokens, but there's also a way to just output the tokens in what looks like (ugly, unformatted) rust code.

**Comment by utaal** [comment]
https://github.com/verus-lang/verus/commit/468b3f2b0f5272b0fb0c4c9cd8469f282a9056cb should fix this -- please try it out and let me know if there are still issues.

Thank you @tjhance and @tenzinhl for diagnosing this.

---

> The Generics node is used for type parameter declarations and allows trait bounds, a where clause, and attributes, which are all appropriate for type declarations. [...]

FYI, `syn` has a `split_for_impl` method on `generics` that prepares generics to be used in an `impl` block header. See https://github.com/verus-lang/verus/commit/468b3f2b0f5272b0fb0c4c9cd8469f282a9056cb#diff-80af9ec7d842dfad7c47bcf3ab1d21d32b4c277b8be00fbac2d184f708254d3aR84-R89

**Comment by tenzinhl** [comment]
> FYI, syn has a split_for_impl method on generics [...]

Oh wow, that's nice haha.
