### ISSUE TITLE
"error[E0433]: failed to resolve: use of undeclared type" multiple times many output errors after an early true error in state_machine! transition

### ISSUE THREAD

**Issue by tenzinhl** [verus-lang/verus#547]
## Intro

Two files. File A contains a state machine defined using `state_machine!`. File B references the state machine in file A.

I made a mistake in file A, which led to a swarm of `rustc` "error[E0433]: failed to resolve: use of undeclared type" errors (one for each time file B references the state machine). My guess is this is because the State machine type doesn't get generated when there's an error in the state machine file?

The swarm of errors are unhelpful and bury the correct/relevant error message at the top. 

## More details

Wrote a transition like:
```rust
transition! {
  commit_start(lbl: Label, frozen_journal: StoreImage, new_journal: AbstractJournal::State, journal_step: AbstractJournal::Step) {
    require lbl.is_CommitStartLabel();
    require pre.ephemeral.is_Known();
    require post.ephemeral.is_Known();
    [...]
}
```

The "true" error gets put at the top of the output:
```rust
error: cannot refer directly to `post` in a transition definition
   --> coordination_layer/CrashTolerantJournal_v.rs:143:21
    |
143 |             require post.ephemeral.is_Known();
    |          
```

But then there's a whole bunch of errors in file B:
```
error[E0433]: failed to resolve: use of undeclared type `CrashTolerantJournal`
  --> coordination_layer/CoordinationSystem_v.rs:51:18
   |
51 |     pub journal: CrashTolerantJournal::State,
   |                  ^^^^^^^^^^^^^^^^^^^^ use of undeclared type `CrashTolerantJournal`
```
^Then that repeats like 50 times.

## The ask

I guess I'm not sure what the right approach here is, is this just something that should be expected to happen? I guess what I as a user expect is that normally if I'm developing outside of a macro even if I make a malformed function inside a class, the class definition should still be visible and the compiler won't complain about "undeclared type".

Not an urgent issue, but would be a nice QoL thing to not have all of this extraneous output when trying to find the source of the problem.

**Comment by tchajed** [comment]
First, this is likely something to go in https://github.com/verus-lang/verus/discussions/387.

Second, I think this is what's expected, unfortunately - it's almost universal for compilers that you should focus on the first error message before looking at others, because subsequent errors might be the result of some error recovery (which might be totally wrong given the compiler encountered an error). If the relevant error _wasn't_ the first but were buried under 50 similar errors that would be a more serious usability issue.

I don't know the details here but in general if something is wrong in the input I wouldn't expect the state machines macro to try to produce output for further error messages; this is partly why you only trust the first error message in a compiler.

**Comment by tenzinhl** [comment]
Oop thanks for the heads-up on #387.

In regards to the latter: got it, thanks. Yeah, I think my hope here was would that it would be possible to keep the type declaration intact. I'm fine with this issue being closed if it doesn't make really make sense

**Comment by utaal** [comment]
No worries about #387, we're currently using that discussion to keep the issue list actionable; I'm happy to move things when necessary. I've moved this issue to https://github.com/verus-lang/verus/discussions/387#discussioncomment-5765553
