### ISSUE TITLE
Rename source/rust_verify/example to source/rust_verify/examples. Otherwise rust-analyzer won't work

### ISSUE THREAD

**Issue by planetoryd** [verus-lang/verus#822]
with `/example` (verus) rust-analyzer told me the files were not included

**Comment by utaal** [comment]
Hi @planetoryd, thank you for the PR. We are intentionally excluding these files from being discovered by cargo/rust-analyzer as they are examples of Verus code, rather than examples of using a Rust library. They should not be in fact discovered by rust-analyzer. Let me know if I clarify further, but I'll go ahead and close this.

Also, if you have further questions, feel free to join the Zulip (see the README).

**Comment by Chris-Hawblitzel** [comment]
By the way, this situation is somewhat my fault; I added the `example` directory to `rust_verify` long, long ago.  More recently, we've discussed moving it do a different place outside of `rust_verify`, so that it would be easier for people to find, and we'll probably do that at some point.
