### ISSUE TITLE
Loop invariant for range insufficient

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#969]
In the attached code (created using `--record`), in `multilogimpl_v.rs` in `UntrustedMultiLogImpl::commit`, you can find an assertion that fails even though it shouldn't:

```
for current_log in 0u32..self.num_logs
    invariant
        0 <= current_log <= self.num_logs,
        self.num_logs == old(self).num_logs,
        ...
{
    assert(current_log < self.num_logs);
    ...
}
```
[2024-01-29-12-08-36.zip](https://github.com/verus-lang/verus/files/14089134/2024-01-29-12-08-36.zip)

**Comment by Chris-Hawblitzel** [comment]
Some context that Jay provided me: in this example, self is being modified inside the loop, so (by design) Verus does not add automatic invariants.

**Comment by Chris-Hawblitzel** [comment]
Since self is being modified inside the loop, there's a potential that the expression self.num_logs could diverge from the iterator that Rust automatically generates for the for loop (when Rust calls into_iter and captures a copy of 0 and self.num_logs).  In this case, you may have to write an invariant about the iterator itself, as in:

```
        fn test_loop() {
            let mut n: u64 = 0;
            for x in iter: 0..10
                invariant n == iter.cur * 3,
            {
                assert(x < 10);
                assert(x == iter.cur);
                n += 3;
            }
            assert(n == 30);
        }
```
The iterator has type `RangeGhostIterator`, which has fields start, cur, and end.  For example, you could add an invariant `iter.end == self.num_logs`.

**Comment by jaylorch** [comment]
Thanks!
